### PR TITLE
Scraped motomalaya website

### PR DESCRIPTION
**Pull request by Ammar-Azman**
- Scraped https://motomalaya.net/blog/
- Added details about the website and the progress
- Added json files

### CODE REVIEW

**Comment by huseinzol05** [comment]
nice nice niceeeeee!

**Comment by huseinzol05** [comment]
let me know when u want me to merge, sebab bila dah merge, kena PR balik

**Comment by Ammar-Azman** [comment]
### Status
Okay done! Completely scraped the website till the end. Boleh PR dah.

**Comment by huseinzol05** [comment]
nice!

**Pull request merged**
